TRUNCATE TABLE element_acces;
TRUNCATE TABLE trousseau_elements;
TRUNCATE TABLE historique_trousseaux;
TRUNCATE TABLE trousseaux;
TRUNCATE TABLE badges;
TRUNCATE TABLE references_cles;
TRUNCATE TABLE batiments;
TRUNCATE TABLE personnes;
TRUNCATE TABLE portes
